In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import entropy

In [2]:
users = pd.read_excel(r'D:\Intern\BANKING\Data\users_data.xlsx')
cards = pd.read_excel(r'D:\Intern\BANKING\Data\cards_data.xlsx')
mcc =  pd.read_excel(r'D:\Intern\BANKING\Data\mcc_codes.xlsx')
transactions = pd.read_excel(r'D:\Intern\BANKING\Data\transactions_data.xlsx')

In [3]:
users.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [4]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2000 non-null   int64
 1   current_age        2000 non-null   int64
 2   retirement_age     2000 non-null   int64
 3   birth_year         2000 non-null   int64
 4   birth_month        2000 non-null   int64
 5   gender             2000 non-null   object
 6   address            2000 non-null   object
 7   latitude           2000 non-null   object
 8   longitude          2000 non-null   float64
 9   per_capita_income  2000 non-null   object
 10  yearly_income      2000 non-null   object
 11  total_debt         2000 non-null   object
 12  credit_score       2000 non-null   int64
 13  num_credit_cards   2000 non-null   int64
dtypes: float64(1), int64(7), object(6)
memory usage: 218.9+ KB

In [5]:
cards.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed
0,4524,825,Visa,Debit,4344676511950440,2022-12-01,623,YES,2,$24295,2002-09-01,2008
1,2731,825,Visa,Debit,4956965974959980,2020-12-01,393,YES,2,$21968,2014-04-01,2014
2,3701,825,Visa,Debit,4582313478255490,2024-02-01,719,YES,2,$46414,2003-07-01,2004
3,42,825,Visa,Credit,4879494103069050,2024-08-01,693,NO,1,$12400,2003-01-01,2012
4,4659,825,Mastercard,Debit (Prepaid),5722874738736010,2009-03-01,75,YES,1,$28,2008-09-01,2009

In [6]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   object
 3   card_type              6146 non-null   object
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   datetime64[ns]
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   object
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   object
 10  acct_open_date         6146 non-null   datetime64[ns]
 11  year_pin_last_changed  6146 non-null   int64
dtypes: datetime64[ns](2), int64(6), object(4)
memory usage: 576.3+ KB

In [7]:
transactions.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,23565628,2024-09-20 08:43:00,44,5748,60.00,Chip Transaction,27092,Medford,OR,97501.0,4829,Bad PIN
1,23252317,2024-07-15 21:19:00,327,3063,20.00,Chip Transaction,27092,Bloomfield,CT,6002.0,4829,Bad PIN
2,22878540,2024-04-27 18:21:00,233,1297,0.00,Chip Transaction,27092,Minneapolis,MN,55433.0,4829,Bad PIN
3,23402443,2024-08-16 14:44:00,114,3398,92.00,Chip Transaction,59935,North Hollywood,CA,91606.0,5499,Bad PIN
4,23267370,2024-07-19 08:16:00,157,1052,23.66,Chip Transaction,59935,Perris,CA,92571.0,5499,Bad PIN

In [8]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157224 entries, 0 to 157223
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              157224 non-null  int64
 1   date            157224 non-null  datetime64[ns]
 2   client_id       157224 non-null  int64
 3   card_id         157224 non-null  int64
 4   amount          157224 non-null  float64
 5   use_chip        157224 non-null  object
 6   merchant_id     157224 non-null  int64
 7   merchant_city   157224 non-null  object
 8   merchant_state  139303 non-null  object
 9   zip             138118 non-null  float64
 10  mcc             157224 non-null  int64
 11  errors          2738 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 14.4+ MB

In [9]:
mcc

     mcc_id                           Description
0      5812         Eating Places and Restaurants
1      5541                      Service Stations
2      7996  Amusement Parks, Carnivals, Circuses
3      5411          Grocery Stores, Supermarkets
4      4784                 Tolls and Bridge Fees
..      ...                                   ...
104    7549                       Towing Services
105    5941                 Sporting Goods Stores
106    5722            Household Appliance Stores
107    3009  Fabricated Structural Metal Products
108    5733    Music Stores - Musical Instruments

[109 rows x 2 columns]

In [10]:
users.describe()

,id,current_age,retirement_age,birth_year,birth_month,longitude,credit_score,num_credit_cards
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,999.500000,45.391500,66.237500,1973.803000,6.439000,-91.554765,709.734500,3.073000
std,577.494589,18.414092,3.628867,18.421234,3.565338,16.283293,67.221949,1.637379
min,0.000000,18.000000,50.000000,1918.000000,1.000000,-159.410000,480.000000,1.000000
25%,499.750000,30.000000,65.000000,1961.000000,3.000000,-97.395000,681.000000,2.000000
50%,999.500000,44.000000,66.000000,1975.000000,7.000000,-86.440000,711.500000,3.000000
75%,1499.250000,58.000000,68.000000,1989.000000,10.000000,-80.130000,753.000000,4.000000
max,1999.000000,101.000000,79.000000,2002.000000,12.000000,-68.670000,850.000000,9.000000

In [11]:
users.isnull().sum()

id                   0
current_age          0
retirement_age       0
birth_year           0
birth_month          0
gender               0
address              0
latitude             0
longitude            0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
dtype: int64

In [12]:
cards.isnull().sum()

id                       0
client_id                0
card_brand               0
card_type                0
card_number              0
expires                  0
cvv                      0
has_chip                 0
num_cards_issued         0
credit_limit             0
acct_open_date           0
year_pin_last_changed    0
dtype: int64

In [13]:
transactions.isnull().sum()

id                     0
date                   0
client_id              0
card_id                0
amount                 0
use_chip               0
merchant_id            0
merchant_city          0
merchant_state     17921
zip                19106
mcc                    0
errors            154486
dtype: int64

In [14]:
transactions.isnull().mean() * 100

id                 0.000000
date               0.000000
client_id          0.000000
card_id            0.000000
amount             0.000000
use_chip           0.000000
merchant_id        0.000000
merchant_city      0.000000
merchant_state    11.398387
zip               12.152089
mcc                0.000000
errors            98.258536
dtype: float64

In [15]:
# merchant state
transactions['merchant_state'] = transactions['merchant_state'].fillna('Unknown')

# zip
transactions['zip'] = transactions['zip'].fillna('Unknown')

# errors
transactions['errors'] = transactions['errors'].fillna('No Error')

In [16]:
# Làm sạch cột về tiền

# cards
cards['credit_limit'] = (
        cards['credit_limit'].replace(r'[\$,]', '', regex = True).astype(float)
)

# users
users['per_capita_income'] = (
        users['per_capita_income'].replace(r'[\$,]', '', regex = True).astype(float)
)

users['yearly_income'] = (
        users['yearly_income'].replace(r'[\$,]', '', regex = True).astype(float)
)

users['total_debt'] = (
        users['total_debt'].replace(r'[\$,]', '', regex = True).astype(float)
)

In [17]:
# How many cards does the user have ?
cards.groupby("client_id").size().describe()

count    2000.000000
mean        3.073000
std         1.637379
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         9.000000
dtype: float64

In [18]:
# How many transactions can be made by card ? 
transactions.groupby("card_id").size().describe()

count     896.000000
mean      175.473214
std       140.814285
min         2.000000
25%        84.000000
50%       136.000000
75%       226.250000
max      1313.000000
dtype: float64

In [19]:
transactions = transactions.copy()
cards_feat = cards.copy()
users_feat = users.copy()

# User cross features
users_feat['debt_to_income'] = (
    users_feat['total_debt'] / users_feat['yearly_income'].replace(0, np.nan)
).replace([np.inf, -np.inf], 0).fillna(0)

users_feat['age_to_retirement'] = (
    users_feat['retirement_age'] - users_feat['current_age']
)

In [20]:
# =========================
# SNAPSHOT GENERATION
# =========================

min_date = transactions['date'].min()
max_date = transactions['date'].max()

OBS_DAYS = 180
PERF_DAYS = 60

snapshot_start = min_date + pd.Timedelta(days=OBS_DAYS)
snapshot_end = max_date - pd.Timedelta(days=PERF_DAYS)

snapshot_dates = pd.date_range(
    start=snapshot_start,
    end=snapshot_end,
    freq='M'   
)

snapshot_dates = pd.to_datetime(snapshot_dates)

print("Snapshot dates:")
for d in snapshot_dates:
    print(d.date())

Snapshot dates:
2022-06-30
2022-07-31
2022-08-31
2022-09-30
2022-10-31
2022-11-30
2022-12-31
2023-01-31
2023-02-28
2023-03-31
2023-04-30
2023-05-31
2023-06-30
2023-07-31
2023-08-31
2023-09-30
2023-10-31
2023-11-30
2023-12-31
2024-01-31
2024-02-29
2024-03-31
2024-04-30
2024-05-31
2024-06-30
2024-07-31
2024-08-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\996847220.py:14: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  snapshot_dates = pd.date_range(

In [21]:
def build_obs_features(
    transactions_df: pd.DataFrame,
    cards_df: pd.DataFrame,
    users_df: pd.DataFrame,
    snapshot_date: pd.Timestamp,
    obs_days: int = 180
) -> pd.DataFrame:
    
    """
    Build observation-window features at client_id level.
    Observation window: [snapshot_date - obs_days, snapshot_date]
    """

    obs_start = snapshot_date - pd.Timedelta(days=obs_days)

    obs_df = transactions_df.loc[
        (transactions_df['date'] > obs_start) &
        (transactions_df['date'] <= snapshot_date)
    ].copy()

    if obs_df.empty:
        return pd.DataFrame(columns=['client_id'])

    # -------------------------
    # Basic transaction flags
    # -------------------------
    obs_df['tr_overnight'] = obs_df['date'].dt.hour.between(0, 5).astype(int)
    obs_df['is_weekend'] = obs_df['date'].dt.dayofweek.isin([5, 6]).astype(int)

    obs_df['insufficient_funds'] = obs_df['errors'].fillna('No Error').str.contains(
        'Insufficient Balance', case=False, na=False
    ).astype(int)

    obs_df['has_error'] = (
        obs_df['errors'].fillna('No Error').ne('No Error')
    ).astype(int)

    high_risk_mccs = [7995, 4829]
    obs_df['high_risk_mcc'] = obs_df['mcc'].isin(high_risk_mccs).astype(int)

    obs_df['is_chip'] = obs_df['use_chip'].fillna('').str.contains('Chip', case=False, na=False).astype(int)
    obs_df['is_swipe'] = obs_df['use_chip'].fillna('').str.contains('Swipe', case=False, na=False).astype(int)
    obs_df['is_online'] = obs_df['use_chip'].fillna('').str.contains('Online', case=False, na=False).astype(int)

    obs_df['tx_month'] = obs_df['date'].dt.to_period('M')
    obs_df['tx_day'] = obs_df['date'].dt.date

    # -------------------------
    # Core aggregates
    # -------------------------
    obs_features = (
        obs_df.groupby('client_id')
        .agg(
            txn_count=('amount', 'count'),
            total_spent=('amount', 'sum'),
            avg_txn=('amount', 'mean'),
            median_txn=('amount', 'median'),
            max_txn=('amount', 'max'),
            min_txn=('amount', 'min'),
            txn_std=('amount', 'std'),

            merchant_diversity=('mcc', 'nunique'),
            merchant_count=('merchant_id', 'nunique'),
            city_diversity=('merchant_city', 'nunique'),
            state_diversity=('merchant_state', 'nunique'),

            active_days=('tx_day', 'nunique'),
            min_date=('date', 'min'),
            max_date=('date', 'max'),

            insufficient_funds_count=('insufficient_funds', 'sum'),
            error_count=('has_error', 'sum'),
            overnight_count=('tr_overnight', 'sum'),
            weekend_count=('is_weekend', 'sum'),
            high_risk_count=('high_risk_mcc', 'sum'),

            chip_count=('is_chip', 'sum'),
            swipe_count=('is_swipe', 'sum'),
            online_count=('is_online', 'sum')
        )
        .reset_index()
    )

    obs_features['txn_std'] = obs_features['txn_std'].fillna(0)

    obs_features['observed_span_days'] = (
        (obs_features['max_date'] - obs_features['min_date']).dt.days + 1
    ).clip(lower=1)

    # -------------------------
    # Ratio features
    # -------------------------
    obs_features['txn_frequency'] = obs_features['txn_count'] / obs_features['observed_span_days']
    obs_features['spending_velocity'] = obs_features['total_spent'] / obs_features['observed_span_days']

    obs_features['spending_volatility'] = (
        obs_features['txn_std'] / obs_features['avg_txn'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['max_to_avg_ratio'] = (
        obs_features['max_txn'] / obs_features['avg_txn'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['insufficient_funds_ratio'] = (
        obs_features['insufficient_funds_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['declined_ratio'] = (
        obs_features['error_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['night_ratio'] = (
        obs_features['overnight_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['weekend_ratio'] = (
        obs_features['weekend_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['high_risk_ratio'] = (
        obs_features['high_risk_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['chip_ratio'] = (
        obs_features['chip_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['swipe_ratio'] = (
        obs_features['swipe_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['online_ratio'] = (
        obs_features['online_count'] / obs_features['txn_count']
    ).fillna(0)

    obs_features['merchant_per_txn_ratio'] = (
        obs_features['merchant_count'] / obs_features['txn_count']
    ).fillna(0)

    # -------------------------
    # Merchant entropy
    # -------------------------
    merchant_entropy_feature = (
        obs_df.groupby('client_id')['mcc']
        .apply(lambda x: entropy(x.value_counts(normalize=True)))
        .rename('merchant_entropy')
        .reset_index()
    )

    obs_features = obs_features.merge(
        merchant_entropy_feature,
        on='client_id',
        how='left'
    )
    obs_features['merchant_entropy'] = obs_features['merchant_entropy'].fillna(0)

    # -------------------------
    # Monthly behavior
    # -------------------------
    monthly_client = (
        obs_df.groupby(['client_id', 'tx_month'])
        .agg(
            monthly_spent=('amount', 'sum'),
            monthly_txn=('amount', 'count')
        )
        .reset_index()
    )

    monthly_stats = (
        monthly_client.groupby('client_id')
        .agg(
            avg_monthly_spent=('monthly_spent', 'mean'),
            std_monthly_spent=('monthly_spent', 'std'),
            avg_monthly_txn=('monthly_txn', 'mean'),
            std_monthly_txn=('monthly_txn', 'std'),
            active_months=('tx_month', 'nunique')
        )
        .reset_index()
    )

    monthly_stats['std_monthly_spent'] = monthly_stats['std_monthly_spent'].fillna(0)
    monthly_stats['std_monthly_txn'] = monthly_stats['std_monthly_txn'].fillna(0)

    def calc_spend_trend(x):
        x = x.sort_values('tx_month')
        if len(x) < 2:
            return 0
        y = x['monthly_spent'].values
        t = np.arange(len(y))
        return np.polyfit(t, y, 1)[0]

    monthly_trend = (
        monthly_client.groupby('client_id')
        .apply(calc_spend_trend)
        .rename('monthly_spend_trend')
        .reset_index()
    )

    obs_features = obs_features.merge(monthly_stats, on='client_id', how='left')
    obs_features = obs_features.merge(monthly_trend, on='client_id', how='left')

    # -------------------------
    # Transaction gap
    # -------------------------
    gap_df = obs_df.sort_values(['client_id', 'date']).copy()
    gap_df['txn_gap'] = gap_df.groupby('client_id')['date'].diff().dt.days

    gap_features = (
        gap_df.groupby('client_id')
        .agg(
            avg_txn_gap_days=('txn_gap', 'mean'),
            std_txn_gap_days=('txn_gap', 'std')
        )
        .reset_index()
    )

    obs_features = obs_features.merge(gap_features, on='client_id', how='left')

    # -------------------------
    # Recency
    # -------------------------
    last_txn = (
        obs_df.groupby('client_id')['date']
        .max()
        .rename('last_txn_date')
        .reset_index()
    )

    last_txn['recency_days'] = (snapshot_date - last_txn['last_txn_date']).dt.days

    obs_features = obs_features.merge(
        last_txn[['client_id', 'recency_days']],
        on='client_id',
        how='left'
    )

    # -------------------------
    # Card features
    # -------------------------
    card_features = (
        cards_df.groupby('client_id')
        .agg(
            total_credit_limit=('credit_limit', 'sum'),
            avg_credit_limit=('credit_limit', 'mean'),
            card_count=('id', 'count'),
            debit_card_count=('card_type', lambda x: x.fillna('').str.contains('Debit', case=False).sum()),
            credit_card_count=('card_type', lambda x: x.fillna('').str.contains('Credit', case=False).sum()),
            chip_card_count=('has_chip', lambda x: (x == 'YES').sum()),
            avg_cards_issued=('num_cards_issued', 'mean')
        )
        .reset_index()
    )

    obs_features = obs_features.merge(card_features, on='client_id', how='left')

    # -------------------------
    # User features
    # -------------------------
    user_features = users_df[[
        'id', 'current_age', 'retirement_age', 'per_capita_income',
        'yearly_income', 'total_debt', 'credit_score', 'num_credit_cards',
        'debt_to_income', 'age_to_retirement'
    ]].rename(columns={'id': 'client_id'})

    obs_features = obs_features.merge(user_features, on='client_id', how='left')

    # -------------------------
    # Cross features
    # -------------------------
    obs_features['spend_to_limit_ratio'] = (
        obs_features['total_spent'] / obs_features['total_credit_limit'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['spend_to_income_ratio'] = (
        obs_features['total_spent'] / obs_features['yearly_income'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['avg_txn_to_income_ratio'] = (
        obs_features['avg_txn'] / obs_features['yearly_income'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['txn_per_card'] = (
        obs_features['txn_count'] / obs_features['card_count'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['spent_per_card'] = (
        obs_features['total_spent'] / obs_features['card_count'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    # Recent window ratios
    last_60_df = obs_df.loc[obs_df['date'] > snapshot_date - pd.Timedelta(days=60)]
    spend_60 = last_60_df.groupby('client_id')['amount'].sum().rename('spend_last_60')
    txn_60 = last_60_df.groupby('client_id')['amount'].count().rename('txn_last_60')

    last_120_df = obs_df.loc[obs_df['date'] > snapshot_date - pd.Timedelta(days=120)]
    spend_120 = last_120_df.groupby('client_id')['amount'].sum().rename('spend_last_120')
    txn_120 = last_120_df.groupby('client_id')['amount'].count().rename('txn_last_120')

    obs_features = obs_features.merge(spend_60, on='client_id', how='left')
    obs_features = obs_features.merge(txn_60, on='client_id', how='left')
    obs_features = obs_features.merge(spend_120, on='client_id', how='left')
    obs_features = obs_features.merge(txn_120, on='client_id', how='left')

    obs_features['spending_acceleration_60_120'] = (
        obs_features['spend_last_60'] / obs_features['spend_last_120'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    obs_features['txn_acceleration_60_120'] = (
        obs_features['txn_last_60'] / obs_features['txn_last_120'].replace(0, np.nan)
    ).replace([np.inf, -np.inf], 0).fillna(0)

    # Metadata
    obs_features['snapshot_date'] = pd.Timestamp(snapshot_date)
    obs_features['obs_start_date'] = pd.Timestamp(obs_start)
    obs_features['obs_end_date'] = pd.Timestamp(snapshot_date)

    # Cleanup
    obs_features = obs_features.drop(columns=['min_date', 'max_date'], errors='ignore')
    obs_features = obs_features.fillna(0)

    return obs_features

In [22]:
ABSTAIN = -1


def _safe_div(a, b):
    return np.divide(a, b, out=np.zeros_like(a, dtype=float), where=(b != 0))


def build_proxy_base_for_snapshot(
    transactions_df: pd.DataFrame,
    snapshot_date: pd.Timestamp,
    perf_days: int = 60,
    obs_days: int = 180,
    alpha: float = 10.0
) -> pd.DataFrame:
    """
    Tạo bảng proxy future-side + context past-side ở cấp client_id.
    Đây chưa phải label, chỉ là base để các labeling functions bỏ phiếu.
    """

    perf_end = snapshot_date + pd.Timedelta(days=perf_days)
    obs_start = snapshot_date - pd.Timedelta(days=obs_days)

    perf_df = transactions_df.loc[
        (transactions_df['date'] > snapshot_date) &
        (transactions_df['date'] <= perf_end)
    ].copy()

    obs_df = transactions_df.loc[
        (transactions_df['date'] > obs_start) &
        (transactions_df['date'] <= snapshot_date)
    ].copy()

    if perf_df.empty:
        return pd.DataFrame()

    # -------------------------
    # Common flags
    # -------------------------
    for df in [perf_df, obs_df]:
        df['insufficient_funds'] = df['errors'].fillna('No Error').str.contains(
            'Insufficient Balance', case=False, na=False
        ).astype(int)

        df['has_error'] = (
            df['errors'].fillna('No Error').ne('No Error')
        ).astype(int)

        high_risk_mccs = [7995, 4829]
        df['high_risk_mcc'] = df['mcc'].isin(high_risk_mccs).astype(int)

        df['tx_day'] = df['date'].dt.date

    # -------------------------
    # Future window stats
    # -------------------------
    future_stats = (
        perf_df.groupby('client_id')
        .agg(
            future_txn_count=('amount', 'count'),
            future_spend=('amount', 'sum'),
            future_avg_txn=('amount', 'mean'),
            future_max_txn=('amount', 'max'),
            future_active_days=('tx_day', 'nunique'),

            future_insufficient_funds_count=('insufficient_funds', 'sum'),
            future_error_count=('has_error', 'sum'),
            future_high_risk_count=('high_risk_mcc', 'sum')
        )
        .reset_index()
        .set_index('client_id')
    )

    # -------------------------
    # Past window stats
    # -------------------------
    if obs_df.empty:
        past_stats = pd.DataFrame(index=future_stats.index)
    else:
        past_stats = (
            obs_df.groupby('client_id')
            .agg(
                past_txn_count=('amount', 'count'),
                past_spend=('amount', 'sum'),
                past_avg_txn=('amount', 'mean'),
                past_max_txn=('amount', 'max'),
                past_active_days=('tx_day', 'nunique'),

                past_insufficient_funds_count=('insufficient_funds', 'sum'),
                past_error_count=('has_error', 'sum'),
                past_high_risk_count=('high_risk_mcc', 'sum')
            )
            .reset_index()
            .set_index('client_id')
        )

    label_base = future_stats.join(past_stats, how='left').fillna(0)

    # -------------------------
    # Smoothed / ratio features
    # -------------------------
    global_high_risk_rate = perf_df['high_risk_mcc'].mean() if len(perf_df) > 0 else 0.0

    label_base['future_high_risk_smoothed'] = (
        label_base['future_high_risk_count'] + alpha * global_high_risk_rate
    ) / (label_base['future_txn_count'] + alpha)

    label_base['future_error_rate'] = _safe_div(
        label_base['future_error_count'].values,
        label_base['future_txn_count'].values
    )
    label_base['past_error_rate'] = _safe_div(
        label_base['past_error_count'].values,
        label_base['past_txn_count'].values
    )

    label_base['future_insufficient_rate'] = _safe_div(
        label_base['future_insufficient_funds_count'].values,
        label_base['future_txn_count'].values
    )
    label_base['past_insufficient_rate'] = _safe_div(
        label_base['past_insufficient_funds_count'].values,
        label_base['past_txn_count'].values
    )

    label_base['velocity_future'] = _safe_div(
        label_base['future_spend'].values,
        label_base['past_spend'].replace(0, np.nan).fillna(0).values
    )

    label_base['txn_velocity_future'] = _safe_div(
        label_base['future_txn_count'].values,
        label_base['past_txn_count'].replace(0, np.nan).fillna(0).values
    )

    label_base['avg_txn_shift'] = _safe_div(
        label_base['future_avg_txn'].values,
        label_base['past_avg_txn'].replace(0, np.nan).fillna(0).values
    )

    label_base['error_rate_delta'] = (
        label_base['future_error_rate'] - label_base['past_error_rate']
    )

    label_base['insufficient_rate_delta'] = (
        label_base['future_insufficient_rate'] - label_base['past_insufficient_rate']
    )

    label_base['high_risk_delta'] = (
        label_base['future_high_risk_smoothed']
        - _safe_div(
            label_base['past_high_risk_count'].values,
            np.maximum(label_base['past_txn_count'].values, 1)
        )
    )

    label_base['snapshot_date'] = pd.Timestamp(snapshot_date)
    label_base['perf_end_date'] = pd.Timestamp(perf_end)

    return label_base.reset_index()

In [23]:
def build_label_matrix(label_base: pd.DataFrame) -> pd.DataFrame:
    """
    Mỗi LF trả về:
    - 1  : positive / distress
    - 0  : negative / non-distress
    - -1 : abstain
    """

    df = label_base.copy()

    q90_velocity = df['velocity_future'].quantile(0.90) if len(df) > 0 else 0
    q95_velocity = df['velocity_future'].quantile(0.95) if len(df) > 0 else 0
    q90_highrisk = df['future_high_risk_smoothed'].quantile(0.90) if len(df) > 0 else 0
    q75_highrisk = df['future_high_risk_smoothed'].quantile(0.75) if len(df) > 0 else 0
    q90_error_delta = df['error_rate_delta'].quantile(0.90) if len(df) > 0 else 0

    L = pd.DataFrame(index=df.index)

    # -------------------------
    # Positive LFs
    # -------------------------
    # LF1: strong signal - repeated insufficient funds
    L['lf_pos_repeat_if'] = np.where(
        df['future_insufficient_funds_count'] >= 2, 1, ABSTAIN
    )

    # LF2: insufficient funds + high error rate
    L['lf_pos_if_plus_error'] = np.where(
        (df['future_insufficient_funds_count'] >= 1) &
        (df['future_error_rate'] >= 0.20),
        1, ABSTAIN
    )

    # LF3: insufficient funds + spending spike
    L['lf_pos_if_plus_velocity'] = np.where(
        (df['future_insufficient_funds_count'] >= 1) &
        (df['velocity_future'] >= max(1.5, q90_velocity)),
        1, ABSTAIN
    )

    # LF4: insufficient funds + risky MCC concentration
    L['lf_pos_if_plus_risky_mcc'] = np.where(
        (df['future_insufficient_funds_count'] >= 1) &
        (df['future_high_risk_smoothed'] >= max(0.15, q90_highrisk)),
        1, ABSTAIN
    )

    # LF5: severe behavior shift without repeated IF but with many alerts
    L['lf_pos_behavioral_shock'] = np.where(
        (df['future_insufficient_funds_count'] == 0) &
        (df['velocity_future'] >= max(2.0, q95_velocity)) &
        (df['error_rate_delta'] >= max(0.10, q90_error_delta)) &
        (df['future_error_count'] >= 2),
        1, ABSTAIN
    )

    # -------------------------
    # Negative LFs
    # -------------------------
    # LF6: completely clean and stable
    L['lf_neg_clean_stable'] = np.where(
        (df['future_insufficient_funds_count'] == 0) &
        (df['future_error_count'] == 0) &
        (df['velocity_future'] >= 0.7) &
        (df['velocity_future'] <= 1.3),
        0, ABSTAIN
    )

    # LF7: low risk behavior, no IF, low risky MCC
    L['lf_neg_lowrisk_pattern'] = np.where(
        (df['future_insufficient_funds_count'] == 0) &
        (df['future_error_rate'] <= 0.05) &
        (df['future_high_risk_smoothed'] <= q75_highrisk),
        0, ABSTAIN
    )

    # LF8: inactive / low activity and clean
    L['lf_neg_low_activity_clean'] = np.where(
        (df['future_insufficient_funds_count'] == 0) &
        (df['future_error_count'] == 0) &
        (df['future_txn_count'] <= 2),
        0, ABSTAIN
    )

    return L

In [24]:
def estimate_lf_weights(label_matrix: pd.DataFrame) -> pd.Series:
    """
    Ước lượng độ tin cậy tương đối của từng LF mà không cần label thật.
    Dựa trên:
    - coverage
    - agreement với phần còn lại
    """

    weights = {}

    for col in label_matrix.columns:
        lf = label_matrix[col]
        covered = lf != ABSTAIN
        coverage = covered.mean()

        if coverage == 0:
            weights[col] = 0.0
            continue

        others = label_matrix.drop(columns=[col])

        agreements = []
        for i in label_matrix.index[covered]:
            other_votes = others.loc[i]
            other_votes = other_votes[other_votes != ABSTAIN]

            if len(other_votes) == 0:
                continue

            pos_votes = (other_votes == 1).sum()
            neg_votes = (other_votes == 0).sum()

            if pos_votes == neg_votes:
                continue

            consensus = 1 if pos_votes > neg_votes else 0
            agreements.append(int(lf.loc[i] == consensus))

        agreement = np.mean(agreements) if len(agreements) > 0 else 0.5

        # weight vừa phải, tránh LF nào lấn át hoàn toàn
        weight = (0.5 + agreement) * np.sqrt(coverage)
        weights[col] = float(np.clip(weight, 0.15, 1.50))

    return pd.Series(weights).sort_values(ascending=False)


def aggregate_weak_labels(
    label_base: pd.DataFrame,
    label_matrix: pd.DataFrame,
    pos_threshold: float = 0.80,
    neg_threshold: float = 0.20
):
    """
    Tạo:
    - label_prob
    - label_confidence
    - distress_label (NaN nếu chưa đủ chắc)
    """

    lf_weights = estimate_lf_weights(label_matrix)

    weighted_pos = pd.Series(0.0, index=label_matrix.index)
    weighted_neg = pd.Series(0.0, index=label_matrix.index)
    covered_weight = pd.Series(0.0, index=label_matrix.index)

    for col in label_matrix.columns:
        w = lf_weights[col]
        vals = label_matrix[col]

        weighted_pos += np.where(vals == 1, w, 0.0)
        weighted_neg += np.where(vals == 0, w, 0.0)
        covered_weight += np.where(vals != ABSTAIN, w, 0.0)

    raw_score = np.where(
        covered_weight > 0,
        (weighted_pos - weighted_neg) / covered_weight,
        0.0
    )

    # map score [-1, 1] -> prob [0, 1]
    label_prob = 1 / (1 + np.exp(-3.0 * raw_score))
    label_confidence = np.maximum(label_prob, 1 - label_prob)

    distress_label = np.where(
        label_prob >= pos_threshold, 1,
        np.where(label_prob <= neg_threshold, 0, np.nan)
    )

    out = label_base.copy()
    out['label_prob'] = label_prob
    out['label_confidence'] = label_confidence
    out['lf_votes_pos'] = (label_matrix == 1).sum(axis=1)
    out['lf_votes_neg'] = (label_matrix == 0).sum(axis=1)
    out['lf_covered'] = (label_matrix != ABSTAIN).sum(axis=1)
    out['distress_label'] = distress_label

    return out, lf_weights

In [25]:
def build_label_for_snapshot_weak(
    transactions_df: pd.DataFrame,
    snapshot_date: pd.Timestamp,
    perf_days: int = 60,
    obs_days: int = 180,
    alpha: float = 10.0,
    pos_threshold: float = 0.80,
    neg_threshold: float = 0.20
):
    label_base = build_proxy_base_for_snapshot(
        transactions_df=transactions_df,
        snapshot_date=snapshot_date,
        perf_days=perf_days,
        obs_days=obs_days,
        alpha=alpha
    )

    if label_base.empty:
        return pd.DataFrame(columns=['client_id', 'distress_label']), pd.DataFrame(), pd.Series(dtype=float)

    label_matrix = build_label_matrix(label_base)
    label_debug, lf_weights = aggregate_weak_labels(
        label_base=label_base,
        label_matrix=label_matrix,
        pos_threshold=pos_threshold,
        neg_threshold=neg_threshold
    )

    label = label_debug[['client_id', 'distress_label']].copy()

    return label, label_debug, lf_weights

In [26]:
def build_snapshot_dataset(
    transactions_df: pd.DataFrame,
    cards_df: pd.DataFrame,
    users_df: pd.DataFrame,
    snapshot_date: pd.Timestamp,
    obs_days: int = 180,
    perf_days: int = 60,
    alpha: float = 10.0,
    pos_threshold: float = 0.80,
    neg_threshold: float = 0.20
):
    obs_features = build_obs_features(
        transactions_df=transactions_df,
        cards_df=cards_df,
        users_df=users_df,
        snapshot_date=snapshot_date,
        obs_days=obs_days
    )

    label, label_debug, lf_weights = build_label_for_snapshot_weak(
        transactions_df=transactions_df,
        snapshot_date=snapshot_date,
        perf_days=perf_days,
        obs_days=obs_days,
        alpha=alpha,
        pos_threshold=pos_threshold,
        neg_threshold=neg_threshold
    )

    if obs_features.empty:
        return pd.DataFrame(), pd.DataFrame(), pd.Series(dtype=float)

    dataset = obs_features.merge(label, on='client_id', how='left')

    # KHÔNG fillna(0) nữa, vì NaN nghĩa là pseudo-label chưa chắc
    dataset = dataset.merge(
        label_debug[
            [
                'client_id',
                'label_prob',
                'label_confidence',
                'lf_votes_pos',
                'lf_votes_neg',
                'lf_covered',
                'future_insufficient_funds_count',
                'future_error_count',
                'future_error_rate',
                'future_high_risk_smoothed',
                'velocity_future'
            ]
        ],
        on='client_id',
        how='left'
    )

    dataset['snapshot_date'] = pd.Timestamp(snapshot_date)

    return dataset, label_debug, lf_weights

In [27]:
all_snapshot_datasets = []
all_label_bases = []
all_lf_weights = []

for snapshot_date in snapshot_dates:
    print(f"Building snapshot: {snapshot_date.date()}")

    snapshot_dataset, snapshot_label_base, snapshot_lf_weights = build_snapshot_dataset(
        transactions_df=transactions,
        cards_df=cards_feat,
        users_df=users_feat,
        snapshot_date=snapshot_date,
        obs_days=180,
        perf_days=60,
        alpha=10.0,
        pos_threshold=0.80,
        neg_threshold=0.20
    )

    if not snapshot_dataset.empty:
        all_snapshot_datasets.append(snapshot_dataset)
        all_label_bases.append(snapshot_label_base)

        tmp = snapshot_lf_weights.rename('weight').reset_index()
        tmp.columns = ['lf_name', 'weight']
        tmp['snapshot_date'] = snapshot_date
        all_lf_weights.append(tmp)

final_dataset = pd.concat(all_snapshot_datasets, ignore_index=True)
final_label_base = pd.concat(all_label_bases, ignore_index=True)
final_lf_weights = pd.concat(all_lf_weights, ignore_index=True)

print("Final dataset shape:", final_dataset.shape)
print("Unique clients:", final_dataset['client_id'].nunique())
print("Num snapshots:", final_dataset['snapshot_date'].nunique())

print("\nPseudo-label availability:")
print(final_dataset['distress_label'].value_counts(dropna=False))

print("\nConfident-label rate:")
print(final_dataset['distress_label'].notna().mean())

print("\nPositive rate among confident labels:")
print(final_dataset.loc[final_dataset['distress_label'].notna(), 'distress_label'].mean())

Building snapshot: 2022-06-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2022-07-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2022-08-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2022-09-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2022-10-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2022-11-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2022-12-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-01-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-02-28

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-03-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-04-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-05-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-06-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-07-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-08-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-09-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-10-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-11-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2023-12-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-01-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-02-29

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-03-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-04-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-05-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-06-30

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-07-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Building snapshot: 2024-08-31

C:\Users\embes\AppData\Local\Temp\ipykernel_15632\3265072595.py:194: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_spend_trend)

Final dataset shape: (8147, 86)
Unique clients: 303
Num snapshots: 27

Pseudo-label availability:
distress_label
0.0    4494
NaN    3040
1.0     613
Name: count, dtype: int64

Confident-label rate:
0.6268565115993617

Positive rate among confident labels:
0.12003132954767966

In [28]:
final_dataset['snapshot_date'].value_counts().sort_index()

snapshot_date
2022-06-30 01:43:00    302
2022-07-31 01:43:00    303
2022-08-31 01:43:00    303
2022-09-30 01:43:00    303
2022-10-31 01:43:00    303
2022-11-30 01:43:00    303
2022-12-31 01:43:00    303
2023-01-31 01:43:00    302
2023-02-28 01:43:00    302
2023-03-31 01:43:00    302
2023-04-30 01:43:00    302
2023-05-31 01:43:00    302
2023-06-30 01:43:00    302
2023-07-31 01:43:00    302
2023-08-31 01:43:00    301
2023-09-30 01:43:00    301
2023-10-31 01:43:00    301
2023-11-30 01:43:00    301
2023-12-31 01:43:00    301
2024-01-31 01:43:00    301
2024-02-29 01:43:00    301
2024-03-31 01:43:00    301
2024-04-30 01:43:00    301
2024-05-31 01:43:00    301
2024-06-30 01:43:00    301
2024-07-31 01:43:00    301
2024-08-31 01:43:00    301
Name: count, dtype: int64

In [29]:
sorted_snapshots = sorted(final_dataset['snapshot_date'].unique())

if len(sorted_snapshots) < 3:
    raise ValueError(">= 3 snapshot để tách train / valid / test")

train_snapshots = sorted_snapshots[:-2]
valid_snapshots = sorted_snapshots[-2:-1]
test_snapshots  = sorted_snapshots[-1:]

train_df = final_dataset[final_dataset['snapshot_date'].isin(train_snapshots)].copy()
valid_df = final_dataset[final_dataset['snapshot_date'].isin(valid_snapshots)].copy()
test_df  = final_dataset[final_dataset['snapshot_date'].isin(test_snapshots)].copy()

print("Train snapshots:", train_snapshots)
print("Valid snapshots:", valid_snapshots)
print("Test snapshots :", test_snapshots)

print("Train shape:", train_df.shape)
print("Valid shape:", valid_df.shape)
print("Test shape :", test_df.shape)

print("Train distress rate:", train_df['distress_label'].mean())
print("Valid distress rate:", valid_df['distress_label'].mean())
print("Test distress rate :", test_df['distress_label'].mean())

Train snapshots: [Timestamp('2022-06-30 01:43:00'), Timestamp('2022-07-31 01:43:00'), Timestamp('2022-08-31 01:43:00'), Timestamp('2022-09-30 01:43:00'), Timestamp('2022-10-31 01:43:00'), Timestamp('2022-11-30 01:43:00'), Timestamp('2022-12-31 01:43:00'), Timestamp('2023-01-31 01:43:00'), Timestamp('2023-02-28 01:43:00'), Timestamp('2023-03-31 01:43:00'), Timestamp('2023-04-30 01:43:00'), Timestamp('2023-05-31 01:43:00'), Timestamp('2023-06-30 01:43:00'), Timestamp('2023-07-31 01:43:00'), Timestamp('2023-08-31 01:43:00'), Timestamp('2023-09-30 01:43:00'), Timestamp('2023-10-31 01:43:00'), Timestamp('2023-11-30 01:43:00'), Timestamp('2023-12-31 01:43:00'), Timestamp('2024-01-31 01:43:00'), Timestamp('2024-02-29 01:43:00'), Timestamp('2024-03-31 01:43:00'), Timestamp('2024-04-30 01:43:00'), Timestamp('2024-05-31 01:43:00'), Timestamp('2024-06-30 01:43:00')]
Valid snapshots: [Timestamp('2024-07-31 01:43:00')]
Test snapshots : [Timestamp('2024-08-31 01:43:00')]
Train shape: (7545, 86)
Valid shape: (301, 86)
Test shape : (301, 86)
Train distress rate: 0.12003381234150465
Valid distress rate: 0.13612565445026178
Test distress rate : 0.10326086956521739

In [30]:
train_use = train_df.loc[train_df['distress_label'].notna()].copy()
valid_use = valid_df.loc[valid_df['distress_label'].notna()].copy()
test_use  = test_df.loc[test_df['distress_label'].notna()].copy()

train_use['distress_label'] = train_use['distress_label'].astype(int)
valid_use['distress_label'] = valid_use['distress_label'].astype(int)
test_use['distress_label']  = test_use['distress_label'].astype(int)

drop_cols = [
    'client_id',
    'snapshot_date',
    'obs_start_date',
    'obs_end_date',
    'distress_label',

    # debug / future-only columns
    'label_prob',
    'label_confidence',
    'lf_votes_pos',
    'lf_votes_neg',
    'lf_covered',
    'future_insufficient_funds_count',
    'future_error_count',
    'future_error_rate',
    'future_high_risk_smoothed',
    'velocity_future'
]

feature_cols = [c for c in final_dataset.columns if c not in drop_cols]

X_train = train_use[feature_cols].copy()
y_train = train_use['distress_label'].copy()
w_train = train_use['label_confidence'].fillna(1.0).clip(0.5, 1.0)

X_valid = valid_use[feature_cols].copy()
y_valid = valid_use['distress_label'].copy()

X_test = test_use[feature_cols].copy()
y_test = test_use['distress_label'].copy()

print("Train size after confident filtering:", len(train_use))
print("Valid size after confident filtering:", len(valid_use))
print("Test size after confident filtering :", len(test_use))
print("Num features:", len(feature_cols))

Train size after confident filtering: 4732
Valid size after confident filtering: 191
Test size after confident filtering : 184
Num features: 71

In [31]:
X_train.to_csv("X_train.csv", index=False, encoding="utf-8-sig")
X_valid.to_csv("X_valid.csv", index=False, encoding="utf-8-sig")
X_test.to_csv("X_test.csv", index=False, encoding="utf-8-sig")

y_train.to_csv("y_train.csv", index=False, encoding="utf-8-sig")
y_valid.to_csv("y_valid.csv", index=False, encoding="utf-8-sig")
y_test.to_csv("y_test.csv", index=False, encoding="utf-8-sig")

pd.DataFrame({"w_train": w_train}).to_csv("w_train.csv", index=False, encoding="utf-8-sig")
pd.Series(feature_cols).to_csv("feature_cols.csv", index=False, header=False, encoding="utf-8-sig")

print("Đã lưu xong X_train, X_valid, X_test, y_train, y_valid, y_test, w_train")

Đã lưu xong X_train, X_valid, X_test, y_train, y_valid, y_test, w_train